apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-app-monitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: demo
  endpoints:
  - port: http
    path: /metrics
